### ISSUE TITLE
[BUG] Dollar sign prefix is ignored

### ISSUE THREAD

**Issue by anonymous1184** [CoffeeChaton/vscode-autohotkey-NekoHelp#10]
# Bug Report

## 🔎 Search keywords

<https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/main/note/code507.md>

## To Reproduce (or provide mp4)

1. Assign a numeric variable prefixed with a dollar sign.

## 🎥 Screenshots/mp4/gif

![image](https://user-images.githubusercontent.com/53758552/227775063-90f26a90-b0f7-4cfc-965c-19a977c791f1.png)

## 💻 Code

```ahk
$1 := "test"
OutputDebug % $1
```

## 🙁 Actual behavior

A `neko helpDA(500)` warning is issued.

## 🙂 Expected behavior

No warning.

## Additional context

The above is valid as per AHK v1.1 variable naming. And makes sense in RegEx matches pseudo-arrays.

**Comment by anonymous1184** [comment]
Duplicate!

**Comment by CoffeeChaton** [comment]
v0.0.32(2023-04-01) fix it now
