### ISSUE TITLE
[BUG] Highlighting inside array/object shorthand declaration

### ISSUE THREAD

**Issue by anonymous1184** [CoffeeChaton/vscode-autohotkey-NekoHelp#13]
# Bug Report

## 🔎 Search keywords

Highlighting

## 🎥 Screenshots/mp4/gif

![image](https://user-images.githubusercontent.com/53758552/231946139-4a90b446-8616-474c-8167-6d35bddc2c6e.png)

## 💻 Code

```ahk
xyz := ""
obj := [foo, bar, baz, continue]
obj := { foo: true, bar: xyz, baz: 000, continue: "string" }
;                                       ^^^^^^^^ Shouldn't be Highlighted
obj := { true: "Yes", false: "No", null: ""}
;        ^^^^         ^^^^^ Shouldn't be Highlighted
obj := { Click: "", MsgBox: "" }
;        ^^^^^ Shouldn't be Highlighted
```

## 🙁 Actual behavior

Object properties and array items are highlighted as if they were language constructs, built-in variables or commands.

## 🙂 Expected behavior

Object properties and array items shouldn't be highlighted (no scope, aka `source.ahk`).

## Additional context

Storage modifiers are kinda in the middle, if you use one as an object property it will highlight but as soon as you add the colon, the highlight goes away. My best guess is that the RegEx pattern requires the word followed by a space.

![image](https://user-images.githubusercontent.com/53758552/231946462-54e04800-d7dc-4231-835d-acfdf02545cb.png)

```ahk
obj := { local: "OK" }
;            ^^ No space, no error
obj := { global : "NOT OK"}
;             ^^^ Space = error
```

**Comment by CoffeeChaton** [comment]
![code](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/d276cf32-e4af-4134-bbc4-685f4fc6e457)

```ahk
xyz := ""
arr := [foo, bar, baz, Click, continue, MsgBox, continue]
;                      ^^^^^ Shouldn't be Highlighted
obj := { foo: true, bar: xyz, baz: 000, continue: "string" }
obj := { true: "Yes", false: "No", null: ""}
;        ^^^^         ^^^^^ Shouldn't be Highlighted
obj := { Click: "", MsgBox: "" }
;        ^^^^^ Shouldn't be Highlighted
```

record idea.

`syntax-highlight` is regex in `.tmLanguage.json`, writing regex is difficult of me.

`semantic-highlight`, in js can know semantic, but [Standard token](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#standard-token-types-and-modifiers) not has `Other` or `meta` or `unknown` type.

if use `semantic-highlight`, may be can use `string` or `property` to cover obj key.
