### ISSUE TITLE
[feat] Directory whiteList Settings

### ISSUE THREAD

**Issue by CoffeeChaton** [CoffeeChaton/vscode-autohotkey-NekoHelp#21]
In addition to the current workspace, automatically scan the Folder,

For people who are not used to [Multi-root Workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces)

1. *warn!* this option is allow this extension try to the get file information by `#include` without workspaces. ([privacy-statement](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp#privacy-statement))

2. still respect `"AhkNekoHelp.files.exclude"` (blackList)

| path                  | Description |
| :-------------------- | :---------- |
| `D:/myAutoHotkey/Lib` | any path    |

```jsonc
{ // settings.json
    "AhkNekoHelp.files.alwaysIncludeFolder": [
        "D:\\Q2", // folder path
        "D:/Q3", // use Linux-style separator Char is OK
    ] // string[] as path[]
}
```

**Comment by CzarOfScripts** [comment]
I want to be precise, will autocomplete from files in these directories always or only if they are connected through `#include`?

**Comment by CoffeeChaton** [comment]
> I want to be precise, will autocomplete from files in these directories always or only if they are connected through `#include`?

1. This option does not require the use of `#include`. It is inspired by AutoHotkey, where certain elements are automatically obtained without the need for `#Include`. (Refer to the [AutoHotkey documentation](https://www.autohotkey.com/docs/v1/Functions.htm#lib).)
2. To enable the parser's `#include` option, use `AhkNekoHelp.files.tryParserIncludeOpt`. (See [Issue #16](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/issues/16).)

**Comment by CzarOfScripts** [comment]
@CoffeeChaton, what do I have to do to make this 100% work? Right now it doesn't work for all #include. What information should I provide?

**Comment by CoffeeChaton** [comment]
You should ask at [#16], since this option has nothing to do with `#include`.

## [#21](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/issues/21)

`"AhkNekoHelp.files.alwaysIncludeFolder"`

This option is used to specify the starting folder for recursive scanning, excluding the current workspace. The following pseudocode illustrates this:

code at <https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/main/src/tools/fsTools/getUriList.ts>

## [#16](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/issues/16)

`"AhkNekoHelp.file.tryParserIncludeOpt"`

[support](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/main/note/config/files.tryParserIncludeOpt.md#support)
1. `Absolute path` like `#Include C:\My Documents\Scripts\Utility Subroutines.ahk`
2. `%A_LineFile% style` like `#Include %A_LineFile%\..\ahk_test.ahk`
3. (beta) try to parser `relative path`, like `#Include b.ahk`


https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/f360f71ee0a3325a1a073b4b8af4c7b61a437a8c/src/AhkSymbol/CAhkInclude.ts#L67-L92


https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/f360f71ee0a3325a1a073b4b8af4c7b61a437a8c/src/command/UpdateCache.ts#L53-L65
