### ISSUE TITLE
[BUG] Signature help -> "never" show return block not working

### ISSUE THREAD

**Issue by alfredomtx** [CoffeeChaton/vscode-autohotkey-NekoHelp#24]
1. Change this setting to `never`
![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/20379136/80fecb7d-53cb-4d41-a565-8896f5a20059)
2. Hover any class function
4. See issue: it should not be showing the return block
![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/20379136/5e5cf8dc-e1e8-4460-9146-be8779b60eff)

## 💻 Code

```ahk
class Test {
    hoverMe() {
        return "this should not be visible on hover"
    }
}

Test.hoverMe()
```

## 🙁 Actual behavior

With the setting set to `never`, it still shows every `return` keyword code inside the function when hovering it.

## 🙂 Expected behavior

When hovering the function with this setting set to `never`, no `return` code blocks would be shown.

## Additional comments

I already reopened VS Code and restarted the PC after setting the setting to `never` and it seems to have no effect.

**Comment by CoffeeChaton** [comment]
![sign](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/7307acd8-a424-48dd-984b-d3e2720d2955)
> signaturehelp

This option is for signatureHelp, triggered by `(,)` and `moving position`, not hover.

next version will provide new option of hover.

**Comment by alfredomtx** [comment]
Ohh sorry! So there is no option currently to **not** show the `return` block of the function?

**Comment by CoffeeChaton** [comment]
will be provided at this weekends

**Comment by CoffeeChaton** [comment]
add new option `"AhkNekoHelp.customize.HoverFuncShowReturnBlock"`
