### ISSUE TITLE
[Feat] Add a delay before displaying the popup.

### ISSUE THREAD

**Issue by boromyr** [CoffeeChaton/vscode-autohotkey-NekoHelp#31]
# Feat Provide

The suggestion popup is too fast and often obscures other code while reading, adding a simple setting to adjust the delay of the popup in milliseconds would be very useful.

**Comment by CoffeeChaton** [comment]
Specifically, which function?

completion?

This is controlled by vscode.

```jsonc
// settings.json
{
    "editor.quickSuggestionsDelay": 10 //ms
}
```

**Comment by boromyr** [comment]
Ok thank you, I was not aware of that, I thought it was managed by the extension.
