### ISSUE TITLE
[Feat] support edge-case format

### ISSUE THREAD

**Issue by murataygunn** [CoffeeChaton/vscode-autohotkey-NekoHelp#34]
![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/17836269/1c4d6bff-9180-4b0e-9756-d406c8422481)

It formats one line if statement as shown on screenshot. Notice that a comma exists after the closing parenthesis.

**Comment by murataygunn** [comment]
Its an Ahk V1 script.

**Comment by CoffeeChaton** [comment]
```ahk
#Requires AutoHotkey v1.1.33+
; #Warn All, MsgBox

MsgBox, % foo(99) ; just 99 -> "caseEnd" , but not has "ELSE"
MsgBox, % foo(0) ; just "caseEnd", not "ELSE"
MsgBox, % foo(1) ; just "caseEnd", not "ELSE"
MsgBox, % foo(2) ; just "caseEnd", not "ELSE"
MsgBox, % foo(3) ; just "caseEnd", not "ELSE"
MsgBox, % foo(4) ; just "caseEnd", not "ELSE"

;@ahk-neko-format-ignore-start
foo(var1) {
    if (var1 = 99), Return "Case99"
        MsgBox, % "99"
    
    if (var1 = 0) , Return "caseA"
    if (var1 = 1) , Return "caseB"
    if (var1 = 2) , Return "caseC"
    if (var1 = 3) , Return "caseD"

    MsgBox, % "ELSE"
    Return "caseEnd"
}
;@ahk-neko-format-ignore-end
```

`if (), XXX` or `if () XXX`, the `XXX` nearly out of control

It is always difficult to perform as expected. I have found similar cases in the past but never had time to write a diagnosis.

<https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/main/TODO/diagCase.ahk>.

---

After 2023-07-05, I always leave the house at 6:30 in the morning and get home closer to 8 in the evening, so I don’t have any private coding.

I know what you want is format support, but for the rare, even unreasonable control flow, formatting is very ineffective. It is confirmed that it will not be supported in the short term.
Please use the code ignore it.

```ahk
;@ahk-neko-format-ignore-start
;@ahk-neko-format-ignore-end
```

---

I haven't seen an example of `if (Expression)` being used with `Comma (multi-statement)`, can you provide an actual use case?
1. <https://www.autohotkey.com/docs/v1/lib/IfExpression.htm#ExMultiStatement>
2. <https://www.autohotkey.com/docs/v1/Variables.htm#comma>

**Comment by CoffeeChaton** [comment]
for edge case format, not supported at the moment.
