### ISSUE TITLE
[Feat] Separate scope for boolean values

### ISSUE THREAD

**Issue by CzarOfScripts** [CoffeeChaton/vscode-autohotkey-NekoHelp#38]
# Feat Provide

## 💻 Exp Code

```ahk
test := A_isCompiled
isActive := false
```

## Additional context

I want to change the color for `false` `true`, but not affect `A_isCompiled` and the like. It doesn't seem correct to me that `boolean` values have no color.

**Comment by CoffeeChaton** [comment]
new separate scope is `variable.other.constant.builtin.boolean.ahk` at next version
