### ISSUE TITLE
[BUG] Problem with completion for global var

### ISSUE THREAD

**Issue by CzarOfScripts** [CoffeeChaton/vscode-autohotkey-NekoHelp#39]
# Bug Report

## To Reproduce (or provide mp4)

I don't know how to replicate this bug.

## 💻 Code

```ahk
global test
global testVar := ""
```

## 🙁 Actual behavior

Sometimes "global *variable_name*" appears in the tooltip when entering a variable name and the variable with "global" is inserted when selected

## 🙂 Expected behavior

I think it's obvious that "global" shouldn't be added when I specify a variable somewhere.

**Comment by CzarOfScripts** [comment]
The problem seems to happen when I try to write a variable declared as global inside some function.

![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/78804737/452e2618-2d80-484d-83b6-57913f43ccf7)

**Comment by CoffeeChaton** [comment]
This is a legacy design that will provide options and be removed by default.

My impression is that when calling within func()/methon(), `global` will be filled in to remind myself that this is a global variable.

**Comment by CoffeeChaton** [comment]
https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/eda50d4a-0138-4a9b-bd60-b745513e62ff

> The default is off, that is, the global keyword is not completed at all.
After it is turned on, it is in the func/methon block. After using global to explicitly reference this option, global will no longer be completed (old behavior). Otherwise, when it is used for the first time, it will be completed once to remind the user.

----

```jsonc
// auto insert `global` keywords of `global-var` in func/method range
"AhkNekoHelp.snippets.autoInsertGlobal": false
```

new option, Is there a better Api name or description?

**Comment by CzarOfScripts** [comment]
Seems perfect to me, I just don't understand the point of writing `global` in a function if the variable is already global?
And is it possible to think of something with parameters when calling a function? All parameters are written inside brackets at once, but it is often very inconvenient.
And I apologize for not creating new topics and writing everything here, but when I enter `%` it immediately closes (that is, two percent appears), I think it was in the editor settings, but I can't find it. I don't want another `closing` to be created when I enter this character.

**Comment by CoffeeChaton** [comment]
> I just don't understand the point of writing global in a function if the variable is already global?

```ahk
global L := 0
global T := 0
global R := 1920
global B := 1080

a()
b()
c()
d()
e()

MsgBox, % R "`n last"

a() {
    local
    MsgBox, % R "`n at a()"
}

b() {
    MsgBox, % R "`n at b()"
}

c() {
    static
    MsgBox, % R "`n at c()"
}

d() {
    local
    R := (0 + 500) / 2
    MsgBox, % R "`n at d()" ;250.000
    ; .....
    ; 500 line
    ; .....
    MsgBox, % R "`n at d()" ; expect to get 1920, but 5
}

e() {
    ; miss local
    R := (0 + 500) / 2
    MsgBox, % R "`n at e()" ; expect not change R value
    ; .....
    ; 500 line
    ; .....
    MsgBox, % R "`n at e()" ; expect to get 1920, but 5
}
```

A personal coding habit, forcing the use of the `global` keyword ,avoid accidental changes to global variables and friendly git code review.

---
> And I apologize for not creating new topics and writing everything here, but when I enter % it immediately closes (that is, two percent appears), I think it was in the editor settings, but I can't find it. I don't want another closing to be created when I enter this character.

change it as https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/commit/70d3569c3e003c628604c39e4578b6e97e2d6753
