### ISSUE TITLE
Moving or renaming a file in the workspace creates unwanted report

### ISSUE THREAD

**Issue by ImmortalPony** [CoffeeChaton/vscode-autohotkey-NekoHelp#4]
Hello!

Thank you for the great extension. It's by far the best ahk extension for vscode (I tried almost all of them)

However I have an issue with extension's report:
It opens a new editor window with a report about file renaming. It's not what I want when I simply rename/move a file in the workspace:
```
this is not ahk, just Report
> "List All #Include"
```

It also opens Output Console wtih the following text:
```
> "please check #Include"
2023-03-11 19:19:30.237 [info] > ["FileRenameEvent"]
```

I didn't find an option to turn off these reports. Could you please tell me how to do this?

**Comment by CoffeeChaton** [comment]
Next version will provide options and disable notifications by default.
Previously, changing filenames/moving files outside of vscode did not trigger these reports.

Originally this was to automatically fix `#incloud` when the file name changed/moved paths, but ahk v1 has too much information in `#incloud` to actually get it at runtime, and I couldn't do the static code analysis and auto-correction, so it caused unnecessary reports.

**Comment by CoffeeChaton** [comment]
close with [v0.0.28](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/releases/tag/v0.0.28(2023-03-13))
