### ISSUE TITLE
[Feat] Support for regions

### ISSUE THREAD

**Issue by CzarOfScripts** [CoffeeChaton/vscode-autohotkey-NekoHelp#40]
# Feat Provide

## 💻 Exp Code

```ahk
; code

; [region]
somethingFunction()
{
; ...
}

; other code
; [endregion]

somethingFunction()
{
; ...
}

; other code

```

## Additional context

I want to be able to collapse a section of code that is wrapped in [region] [endregion], this is usually supported everywhere.

**Comment by ibrahim601g** [comment]
Yes. That would be very nice.

**Comment by CoffeeChaton** [comment]
The `.configuration.json` provided by ms/vscode has not provided the configuration of multiple folding blocks until now. What I configured here is `/*` and `*/`. I think I need to copy the vscode default `FoldingRangeProvider`, this is not difficult, I have implemented it directly but it has not been released.

**Comment by CzarOfScripts** [comment]
Few people write `endRegion`, it's usually `endregion`, but thanks!)

**Comment by CoffeeChaton** [comment]
> Few people write `endRegion`, it's usually `endregion`, but thanks!)

support `endRegion` / `endregion` now.

hi~ @ibrahim601g and @CzarOfScripts 

i am added new `; [endregion]` variants like `;#endregion`, as well as some enhancements in the new version, you can see it at issues #88.
