### ISSUE TITLE
[BUG] Problem with displaying inlint hint

### ISSUE THREAD

**Issue by CzarOfScripts** [CoffeeChaton/vscode-autohotkey-NekoHelp#41]
# Bug Report

## 🎥 Screenshots/mp4/gif

![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/78804737/d14e2862-a228-4e9d-a8e7-c1c4ecb79298)

## 💻 Code

```ahk
for _i, line in StrSplit(RegExReplace(textBeforeImage, "\$product_name", productList), "\n")
{

}
```

## 🙁 Actual behavior

The position for "string:" is incorrect.

## 🙂 Expected behavior

Obviously, the position for "string:" is incorrect.

## Additional context

I think it is also a mistake, for I expect the prompt to come after the space.
![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/78804737/b7892091-b1db-41de-a3ea-255971bb5aa5)

Here's what it would look like in TS:
![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/78804737/c72f9955-70c7-4dff-b09e-90091e09c13f)

**Comment by CoffeeChaton** [comment]
![2024-02-10_213802](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/78c3931e-47a8-44cd-9c1d-a7fca1b81f60)

fix it now, I don’t know when it broke.

**Comment by CzarOfScripts** [comment]
Still displayed before the space bar
![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/78804737/1a225ffc-c80d-42a8-9182-d674ea2e5f3e)

**Comment by CoffeeChaton** [comment]
OK, I only fixed func and forgot about cmd at last var.

![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/93636a20-7d91-4258-abe3-267cad6535e6)
> cmd inlint hint will fix at next var.

**Comment by CzarOfScripts** [comment]
Maybe you should put a space at the end of `inlineHint`? Otherwise it doesn't look nice.
