### ISSUE TITLE
[Feat] ColorProvider (color-picker)

### ISSUE THREAD

**Issue by CoffeeChaton** [CoffeeChaton/vscode-autohotkey-NekoHelp#50]
# Feat Provide

## 🔎 Search keywords

<https://code.visualstudio.com/docs/languages/html#_color-picker>

<https://www.autohotkey.com/docs/v1/lib/Progress.htm#colors>

## 💻 Exp Code

```ahk

;@ahk-neko-ignore-fn 999 line; at 2024/4/25 16:59:28 ; var is assigned but never used.

#Requires AutoHotkey v1.1.33+

;https://www.autohotkey.com/docs/v1/lib/Gui.htm#Font
Gui, Add, Text, cRed, My Text

Gui, Color, WindowColor, ControlColor
Gui, Color, EEAA99

WinSet, TransColor, Color
WinSet, TransColor, EEAA99

PixelSearch, OutputVarX, OutputVarY, X1, Y1, X2, Y2, ColorID, Variation, Mode ;https://www.autohotkey.com/docs/v1/lib/PixelSearch.htm
PixelSearch, OutputVarX, OutputVarY, X1, Y1, X2, Y2, 0x444444, Variation, Mode

Menu, MenuName, Color, ColorValue, Single ;https://www.autohotkey.com/docs/v1/lib/Menu.htm#Color
Menu, MenuName, Color, cRED, Single ;https://www.autohotkey.com/docs/v1/lib/Menu.htm#Color
;                      ^Red

Gui, Add, ListView, cEEAA99, ; https://www.autohotkey.com/docs/v1/lib/ListView.htm


; https://www.autohotkey.com/docs/v1/lib/ListView.htm
; Add a space after each color option if there are any more options that follow it.
; For example: `cbRed` `ct900000` `cwBlue`.
cbRed
ct900000
cwBlue
```

## Additional context

After selecting a color, if there is a corresponding color, you can try right-clicking to HTML COLOR NAME.

<https://youtu.be/Vi1AQxeKF2Y>

![alt text](https://raw.githubusercontent.com/CoffeeChaton/vscode-autohotkey-NekoHelp/main/image/Changelog/v0-0-56--issuse-50--color-picker.jpg)

**Comment by CoffeeChaton** [comment]
- [x] lint "#0x00000" or "0x000000" if start with `"` need and with`"` , ...and more lint?
- [x] use `;@ahk-neko-` to close it
- [x] add config `main switch`
- [x] ~add config to avoid let `ctRed` `red` to color as `string[]`~
- [x] add config to change default is `00ff00` or `00FF00` (LowerCase / UpperCase)

**Comment by CoffeeChaton** [comment]
Switch the filling style

1. FF0000 (all upperCase)
2. ff0000 (all lowercase)
3. red (all lowercase, if has [Color name](https://www.autohotkey.com/docs/v1/lib/Progress.htm#colors))
4. Red (Capitalize first letter)


https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/7528859d-4774-49ec-b2fc-d9ae62937a78

**Comment by CzarOfScripts** [comment]
![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/78804737/a2274e3e-26df-42f4-a7d8-ad4c8acac502)

I think something is clearly wrong)

**Comment by CoffeeChaton** [comment]
> I think something is clearly wrong

A. I don’t know your Value1 and value2, what’s the problem?

1. Color-picker is before of inlayHints. I give vscode the same position. However, who is before is determined by vscode and I can't change it.
2. Display color-picker for non-color values? My current plan is to actively display color-picker on all occasions as long as the value looks like a color.

B. `(#000000)` The color value enclosed in brackets will be repaired.
