### ISSUE TITLE
Rules 120 and 126 error

### ISSUE THREAD

**Issue by anonymous1184** [CoffeeChaton/vscode-autohotkey-NekoHelp#6]
First, let me start by thanking you for the great work you have done. This is not just another copy of the same extension with a couple of modifications, this is truly helpful. Wish I could find out about it before.

I do have some small issues that I haven't reported as I'm moving from v1.1, however this one is hard to let slip.

A short-circuit evaluation is marked as a warning (\#120), subsequently forced expressions are marked as errors (\#126):

```ahk
#Warn All

(Fn0() && Echo())
(Fn1() && Echo())
MsgBox % "No runtime warning/errors"

Fn0() {
    return false
}

Fn1() {
    return true
}

Echo() {
    OutputDebug ECHO
}
```

**Comment by CoffeeChaton** [comment]
I incorrectly parsed it as [Method part2](https://www.autohotkey.com/docs/v1/Scripts.htm#continuation)
It will probably be repaired by the weekend, thank you very much for your report!
