### ISSUE TITLE
Disable command options display

### ISSUE THREAD

**Issue by marius-sucan** [CoffeeChaton/vscode-autohotkey-NekoHelp#79]
Please add an option to hide command options in-line.

This
OnMessage(0x202, "WM_LBUTTONup")

... iis displayed as:
OnMessage(MsgNumber: 0x202, FunctionName: "WM_LBUTTONup")

How to disable displaying the options of built-in commands?

I want it to display:
OnMessage(0x202, "WM_LBUTTONup")

Best regards, Marius.

**Comment by CoffeeChaton** [comment]
```jsonc
{
// settings.json
"AhkNekoHelp.inlayHints.AMainSwitch": true,
"AhkNekoHelp.inlayHints.parameterNamesEnabled": "all"
}
```

Or, you just want to hide AHK built-in func/cmd inlayHints ?

**Comment by marius-sucan** [comment]
I want a UI option at settings, please .... I want to hide MsgNumber, FunctionNAME and Value, Filename, inline:
![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/35074874/210cab6a-ae66-4377-8d19-e4fe59aa4b49)

**Comment by marius-sucan** [comment]
It should show something like this:
![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/35074874/c11dddf1-a043-448c-8bac-e9e833f4d459)

Not that additional crap, that describes each parameter inline.

**Comment by CoffeeChaton** [comment]
```jsonc
{
"AhkNekoHelp.inlayHints.AMainSwitch": false
}
```

Turn off all inlayHints , before new var? ( I forgot to change it to false above)

![image](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/4d1b1efa-84f3-4bb9-bf1e-c54b9cb26052)

For built-in functions/commands, showing param signatures seems a bit redundant...
I would provide new options to show only user-defined functions, to show parameter signatures.

---
Any other thoughts lately?

**Comment by marius-sucan** [comment]
Thank you .

I deactivated: main switch of inlay Hints. 

It is what I wanted. Works well. It should be OFF by default.

Yes , I agree it would be redundant to add another option.

Best regards, Marius.
