### ISSUE TITLE
[BUG] syntax-highlight

### ISSUE THREAD

**Issue by CoffeeChaton** [CoffeeChaton/vscode-autohotkey-NekoHelp#9]
# Bug Report

## 🔎 Search keywords

If possible, please help me copy the link and point out which item is wrong.

1. [syntax-highlight](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp#better-highlight)

## 🎥 Screenshots

![image](https://user-images.githubusercontent.com/53758552/227716199-8bd4e04c-87be-4262-914c-282d7e82f77a.png)
> if is [syntax-highlight](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#semantic-theming) ,in addition to your preferred theme, please provide a screenshot of [One Dark Pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) theme for me.

## 💻 Code

```ahk
; not yet 🙁
```

## 🙁 Actual behavior

look image.

## 🙂 Expected behavior

look image.

## Additional context

> [image](https://user-images.githubusercontent.com/53758552/227716199-8bd4e04c-87be-4262-914c-282d7e82f77a.png) - The column on the left beside the proper scopes has different colors that helped me to see what I was doing, the column in the middle is how is supposed to look and the right column is the current version. Also for this, I've disabled the bracket pair colorization and the bracket pairs lines (horizontal/vertical).

split from <https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/issues/7#issuecomment-1483810591>
@anonymous1184

I hope to reply with a text file, so that I can discuss one by one. Editing pictures is a painful thing for me.😎

**Comment by anonymous1184** [comment]
That was not related to your extension. You can nuke this.

**Comment by CoffeeChaton** [comment]
1. Because of laziness, I didn't verify the input one by one, but I paid attention to my private code base, and I haven't seen it yet, and the part that cannot be rendered as an annotation.
2. Generally speaking, the difference between the unresolved color and the color of the annotation is enough to be recognized, and considering that the following code is legal and reasonable.

```ahk
MsgBox, str;str;str~~~~~~~ hi i am str0; ;comment need A_Space or A_Tab before ;
```
