### ISSUE TITLE
[Feat] Help me turn off warnings.

### ISSUE THREAD

**Issue by EddiGits** [CoffeeChaton/vscode-autohotkey-NekoHelp#93]
Could you please help me turn off the warnings and remove the red underline? If turning off the warnings is not possible, that's fine, but I don't want the red underline.

When I use something like:
``` 
if ExtraPopupTitle != 
if StatusOfOrder contains Ready,Stopped,Incomplete
```
I am used to doing this without brackets, but it shows a red line stating that it is incorrect usage. How can I turn off that warning? It's somewhat annoying.

Also, when I type something any keyword like `InputBox` and press enter, all the default commands automatically fill in like:
```
InputBox, OutputVar, % "Title", % "Prompt", HIDE, Width, Height, X, Y, Locale, Timeout_Sec, % "Default_Str"
```
Is there a way to turn this off? Most of the time, I do not need these.

Thank you very much!

**Comment by CzarOfScripts** [comment]
Seconded the last part, very infuriating for msgBox.

**Comment by CoffeeChaton** [comment]
---
about diag `code210` add new option to close it

```jsonc
// settings.json
{
    "AhkNekoHelp.Diag.code209": false, // if StatusOfOrder contains Ready,Stopped,Incomplete
    "AhkNekoHelp.Diag.code210": false, // new config  ---> if ExtraPopupTitle != 
}
```

---
about cmd completion

- plan1 write you funtion like (recommend)

```ahk
#Requires AutoHotkey v1.1.33+

v := InputBoxBase("some Title", "some Prompt")

MsgBox, % "v is " v


MsgBoxFull(Options, Title, Text, Timeout_Sec) {
    MsgBox, Options, Title, Text, Timeout_Sec
}

InputBoxBase(Title, Prompt) {
    InputBox, OutputVar, %Title%, %Prompt%
    Return, OutputVar
}
```

- plan2 edit syntax file (Not recommended)

![image](https://github.com/user-attachments/assets/e41fecab-82c4-4e85-aa4e-d123e21d8853)


This customization is a little more difficult, but you can
1. Press `F12` on `Msgbox` to jump to the definition file of cmd file `Command.en.ahk.json` or `Command.zh-cn.ahk.json`
2. Cancel the read-only attribute of the file on the Windows desktop
3. Edit the body tag of the file [use snippet-syntax](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax)
4. Restart extension/vscode to take effect
(But it will be remade after the expansion is updated)


Or if you see a better way, please give me an example.

**Comment by CoffeeChaton** [comment]
Or do you mean that the command does not complete the parameters, but only the command keyword itself?

**Comment by EddiGits** [comment]
Thank you very much. I will try this. Keep up the good work!
